# ????
spring.application.name=yjx

# ?????
server.port=8081

# SQLite ?????
spring.datasource.url=jdbc:sqlite:todo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Hibernate ??
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT ??
jwt.secret=GNYWfZGrt2R8KvcSrFuPNDRRBdpvnKfEJuU8aUX6pwsCCBnBw2nT3MvFKUTEMWWxSWQF2kkmzGcrNenwdPCMXQSM67WcNpax25rwTxya3PAC2E45BAHtufpZpGwF8YNeE2fSyHaYnWzPQWsjhVBVtAxCwXZQKnDQnjSBdnDDfaaPHdpRXHbDV8kezad3fdDvUPjWs7CrUDNV3D6SHFyxRcW24WyGThS7h8rTSwJhQFHt4WryKkGVRR8p8XW88nGh
jwt.expiration=86400000

# ????
logging.level.com.example.todo=DEBUG